Repository GOSOPT-CDS-Homesool/client, pull requests merged in 2023-05, with the labels that each got.

#2 theme
  package.json
  src/style/globalStyle.ts
  src/style/theme.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#29 Feat#25/payment confirmation
  src/@components/orderPaymentPage/orderConfirmation.tsx
  src/@components/orderPaymentPage/paymentConfirmation/ amountOfPayment.tsx
  src/@components/orderPaymentPage/paymentConfirmation/ discountCalculation.tsx
  src/@components/orderPaymentPage/paymentConfirmation/paymentMethod.tsx
  src/@pages/orderPayment.tsx
  src/assets/icon/checkIc.svg
  src/assets/icon/noneCheckIc.svg
  src/assets/index.ts
  src/style/theme.ts
Labels: feat, design

#24 Feat#22/order confirmation
  src/@components/orderPaymentPage/orderConfirmation.tsx
  src/@components/orderPaymentPage/orderConfirmation/orderProductInfo.tsx
  src/@components/orderPaymentPage/orderConfirmation/ordererInfo.tsx
  src/@components/orderPaymentPage/orderConfirmation/requestForDelivery.tsx
  src/@components/orderPaymentPage/orderConfirmation/shippingAddress.tsx
  src/@components/orderPaymentPage/paymentConfirmation/ amountOfPayment.tsx
  src/@components/orderPaymentPage/paymentConfirmation/ discountCalculation.tsx
  src/@components/orderPaymentPage/paymentConfirmation/paymentMethod.tsx
  src/@pages/orderPayment.tsx
  src/Router.tsx
  src/assets/icon/checkIc.svg
  src/assets/icon/noneCheckIc.svg
  src/assets/icon/sideOpenIcon.svg
  src/assets/icon/triangleOpenIc.svg
  src/assets/index.ts
  src/core/shippingMessageData.ts
  src/style/theme.ts
  src/type/shippingMessageType.ts
Labels: feat, design

#21 Feat#20/product detail info
  src/@components/common/GrayGap.tsx
  src/@components/detailPage/basicInfo/productBasicInfo.tsx
  src/@components/detailPage/productDetailInfo/productInfo.tsx
  src/@components/orderPaymentPage/orderConfirmation.tsx
  src/@components/orderPaymentPage/orderConfirmation/orderProductInfo.tsx
  src/@components/orderPaymentPage/orderConfirmation/ordererInfo.tsx
  src/@components/orderPaymentPage/orderConfirmation/requestForDelivery.tsx
  src/@components/orderPaymentPage/orderConfirmation/shippingAddress.tsx
  src/@components/orderPaymentPage/paymentConfirmation/ amountOfPayment.tsx
  src/@components/orderPaymentPage/paymentConfirmation/ discountCalculation.tsx
  src/@components/orderPaymentPage/paymentConfirmation/paymentMethod.tsx
  src/@pages/detail.tsx
  src/@pages/orderPayment.tsx
  src/Router.tsx
  src/assets/assets.d.ts
  src/assets/icon/checkIc.svg
  src/assets/icon/closeIcon.svg
  src/assets/icon/noneCheckIc.svg
  src/assets/icon/openIcon.svg
  src/assets/icon/sideOpenIcon.svg
  src/assets/icon/triangleOpenIc.svg
  src/assets/image/closeBasicInfoImg.png
  src/assets/image/closeProductInfoImg.png
  src/assets/image/openBasicInfoImg.png
  src/assets/image/openProductInfoImg.png
  src/assets/index.ts
  src/core/shippingMessageData.ts
  src/style/theme.ts
  src/type/shippingMessageType.ts
  tsconfig.json
Labels: feat, design

#19 Feat#18 detail/choice delivery
  src/@components/common/GrayGap.tsx
  src/@components/detailPage/basicInfo/productBasicInfo.tsx
  src/@components/detailPage/detailProduct/choiceDelivery.tsx
  src/@components/detailPage/detailProduct/detailOrderInfo.tsx
  src/@components/detailPage/detailProduct/failBuyButton.tsx
  src/@components/detailPage/detailProduct/orderChoice.tsx
  src/@components/detailPage/detailProduct/orderContents.tsx
  src/@components/detailPage/detailProduct/successBuyButton.tsx
  src/@components/detailPage/productDetailInfo/productInfo.tsx
  src/@components/orderPaymentPage/orderConfirmation.tsx
  src/@components/orderPaymentPage/orderConfirmation/orderProductInfo.tsx
  src/@components/orderPaymentPage/orderConfirmation/ordererInfo.tsx
  src/@components/orderPaymentPage/orderConfirmation/requestForDelivery.tsx
  src/@components/orderPaymentPage/orderConfirmation/shippingAddress.tsx
  src/@components/orderPaymentPage/paymentConfirmation/ amountOfPayment.tsx
  src/@components/orderPaymentPage/paymentConfirmation/ discountCalculation.tsx
  src/@components/orderPaymentPage/paymentConfirmation/paymentMethod.tsx
  src/@pages/detail.tsx
  src/@pages/orderPayment.tsx
  src/Router.tsx
  src/assets/assets.d.ts
  src/assets/icon/alertCircleIc.svg
  src/assets/icon/checkIc.svg
  src/assets/icon/checkRadioIc.svg
  src/assets/icon/closeIcon.svg
  src/assets/icon/nonCheckRadioIc.svg
  src/assets/icon/noneCheckIc.svg
  src/assets/icon/openIcon.svg
  src/assets/icon/sideOpenIcon.svg
  src/assets/icon/triangleOpenIc.svg
  src/assets/image/closeBasicInfoImg.png
  src/assets/image/closeProductInfoImg.png
  src/assets/image/openBasicInfoImg.png
  src/assets/image/openProductInfoImg.png
  src/assets/index.ts
  src/core/shippingMessageData.ts
  src/style/theme.ts
  src/type/shippingMessageType.ts
  tsconfig.json
Labels: design

#30 Feat#28 detail page/product review
  src/@components/productReiviewList.tsx
  src/@components/productReview.tsx
  src/assets/icon/right.svg
  src/assets/index.ts
  src/core/reviewData.ts
  src/type/reviewDataType.ts
Labels: feat, design

#16 Feat#9 common/footer
  src/@components/common/.keep
  src/@components/common/commonFooter.tsx
  src/@pages/myPage.tsx
  src/assets/icon/commonFooterIc.svg
  src/assets/icon/footerHomeActiveIc.svg
  src/assets/icon/footerHomeIc.svg
  src/assets/icon/footerMyActiveIc.svg
  src/assets/icon/footerMyIc.svg
  src/assets/index.ts
Labels: feat, design

#15 Feat#7 mypage/list UI
  src/@components/common/.keep
  src/@components/common/commonFooter.tsx
  src/@components/common/listBox.tsx
  src/@components/common/pageFooter.tsx
  src/@components/common/title.tsx
  src/@components/myPage/customerCenter.tsx
  src/@components/myPage/myShopping.tsx
  src/@components/myPage/totalOrder.tsx
  src/@components/myPage/totalOrderList.tsx
  src/@pages/myPage.tsx
  src/assets/icon/commonFooterIc.svg
  src/assets/icon/footerHomeActiveIc.svg
  src/assets/icon/footerHomeIc.svg
  src/assets/icon/footerIc.svg
  src/assets/icon/footerMyActiveIc.svg
  src/assets/icon/footerMyIc.svg
  src/assets/index.ts
  src/core/myPage.ts
  src/type/mypage.ts
Labels: feat, design

#41 Feat#40 detail/review
  .env
  src/@components/common/pageFooter.tsx
  src/@components/common/top.tsx
  src/@components/detailPage/basicInfo/productBasicInfo.tsx
  src/@components/detailPage/detailAsk.tsx
  src/@components/detailPage/detailAskBox.tsx
  src/@components/detailPage/detailProduct/detailOrderInfo.tsx
  src/@components/detailPage/productDetailInfo/productInfo.tsx
  src/@components/detailPage/productReview/productReiviewList.tsx
  src/@components/detailPage/productReview/productReview.tsx
  src/@components/homePage/Twinkle.tsx
  src/@components/homePage/brandNew.tsx
  src/@components/homePage/card/like.tsx
  src/@components/homePage/card/price.tsx
  src/@components/homePage/card/soldOut.tsx
  src/@components/homePage/card/stars.tsx
  src/@components/homePage/card/stock.tsx
  src/@components/homePage/card/tags.tsx
  src/@components/homePage/carousel/brandNewCard.tsx
  src/@components/homePage/carousel/card.tsx
  src/@components/homePage/carousel/cardList.tsx
  src/@components/homePage/carousel/cardListHeader.tsx
  src/@components/homePage/carousel/reviewCard.tsx
  src/@components/homePage/carousel/reviewCardList.tsx
  src/@components/homePage/review.tsx
  src/@components/homePage/subscribe.tsx
  src/@components/homePage/thisMonth.tsx
  src/@components/myPage/totalOrderList.tsx
  src/@components/orderPaymentPage/successModal.tsx
  src/@pages/detail.tsx
  src/@pages/home.tsx
  src/@pages/myPage.tsx
  src/@pages/orderPayment.tsx
  src/App.tsx
  src/Router.tsx
  src/api/detailAsk.tsx
  src/api/detailReview.tsx
  src/api/userData.tsx
  src/assets/icon/detailFoldIc.svg
  src/assets/icon/detailNoReviewIc.svg
  src/assets/icon/detailUnfoldIc.svg
  src/assets/icon/footerIc.svg
  src/assets/icon/myPageAdsIc.svg
  src/assets/image/homeAdsImage.png
  src/assets/image/myPageAdsImage.png
  src/assets/image/subscribe_banner.svg
  src/assets/image/top.png
  src/assets/index.ts
  src/core/allReviewData.ts
  src/core/productDataDH.ts
  src/type/allReviewDataType.ts
  src/type/detailIdProps.ts
  src/type/productDataTypeDH.ts
  src/type/tagsDataType.ts
Labels: feat

#38 Feat#35 mypgae/get user data
  .env
  src/@components/common/pageFooter.tsx
  src/@components/common/top.tsx
  src/@components/detailPage/basicInfo/productBasicInfo.tsx
  src/@components/detailPage/detailAsk.tsx
  src/@components/detailPage/detailAskBox.tsx
  src/@components/detailPage/detailProduct/detailOrderInfo.tsx
  src/@components/detailPage/productDetailInfo/productInfo.tsx
  src/@components/detailPage/productReview/productReiviewList.tsx
  src/@components/detailPage/productReview/productReview.tsx
  src/@components/homePage/Twinkle.tsx
  src/@components/homePage/brandNew.tsx
  src/@components/homePage/card/like.tsx
  src/@components/homePage/card/price.tsx
  src/@components/homePage/card/soldOut.tsx
  src/@components/homePage/card/stars.tsx
  src/@components/homePage/card/stock.tsx
  src/@components/homePage/card/tags.tsx
  src/@components/homePage/carousel/brandNewCard.tsx
  src/@components/homePage/carousel/card.tsx
  src/@components/homePage/carousel/cardList.tsx
  src/@components/homePage/carousel/cardListHeader.tsx
  src/@components/homePage/carousel/reviewCard.tsx
  src/@components/homePage/carousel/reviewCardList.tsx
  src/@components/homePage/review.tsx
  src/@components/homePage/subscribe.tsx
  src/@components/homePage/thisMonth.tsx
  src/@components/myPage/couponInfoBox.tsx
  src/@components/myPage/totalOrderList.tsx
  src/@components/myPage/userProfile.tsx
  src/@components/orderPaymentPage/successModal.tsx
  src/@pages/detail.tsx
  src/@pages/home.tsx
  src/@pages/myPage.tsx
  src/@pages/orderPayment.tsx
  src/App.tsx
  src/Router.tsx
  src/api/detailAsk.tsx
  src/api/detailReview.tsx
  src/api/userData.tsx
  src/assets/icon/detailFoldIc.svg
  src/assets/icon/detailNoReviewIc.svg
  src/assets/icon/detailUnfoldIc.svg
  src/assets/icon/footerIc.svg
  src/assets/icon/myPageAdsIc.svg
  src/assets/image/homeAdsImage.png
  src/assets/image/myPageAdsImage.png
  src/assets/image/subscribe_banner.svg
  src/assets/image/top.png
  src/assets/index.ts
  src/core/allReviewData.ts
  src/core/productDataDH.ts
  src/type/allReviewDataType.ts
  src/type/detailIdProps.ts
  src/type/productDataTypeDH.ts
  src/type/tagsDataType.ts
  src/type/userDataType.ts
Labels: feat

#46 Feat#33 detail/api연결
  package.json
  src/@components/detailPage/detailProduct/detailOrderInfo.tsx
  src/@components/detailPage/detailProduct/failBuyButton.tsx
  src/@components/detailPage/detailProduct/likeButton.tsx
  src/@components/detailPage/detailProduct/orderChoice.tsx
  src/@components/detailPage/detailProduct/orderContents.tsx
  src/@components/detailPage/detailProduct/successBuyButton.tsx
  src/@components/detailPage/productDetailInfo/productInfo.tsx
  src/@components/orderPaymentPage/orderConfirmation.tsx
  src/@components/orderPaymentPage/orderConfirmation/orderProductInfo.tsx
  src/@components/orderPaymentPage/orderConfirmation/ordererInfo.tsx
  src/@components/orderPaymentPage/orderConfirmation/shippingAddress.tsx
  src/@components/orderPaymentPage/paymentConfirmation/ amountOfPayment.tsx
  src/api/alcoholData.tsx
  src/api/postPurchaseData.tsx
  src/assets/icon/datailProductImg.svg
  src/assets/image/closeProductInfoImg.png
  src/assets/image/openProductInfoImg.png
  src/assets/index.ts
  src/type/OrderOptionType.ts
  src/type/productDataType.ts
  yarn.lock
Labels: feat, design

#48 Feat#47 merge/merge
  package.json
  src/@components/detailPage/detailProduct/detailOrderInfo.tsx
  src/@components/detailPage/detailProduct/failBuyButton.tsx
  src/@components/detailPage/detailProduct/orderChoice.tsx
  src/@components/detailPage/detailProduct/orderContents.tsx
  src/@components/detailPage/detailProduct/successBuyButton.tsx
  src/@components/homePage/carousel/card.tsx
  src/@components/homePage/carousel/cardList.tsx
  src/@components/orderPaymentPage/orderConfirmation.tsx
  src/@components/orderPaymentPage/orderConfirmation/orderProductInfo.tsx
  src/@components/orderPaymentPage/paymentConfirmation/ amountOfPayment.tsx
  src/@components/orderPaymentPage/paymentConfirmation/ discountCalculation.tsx
  src/@pages/myPage.tsx
  src/@pages/orderPayment.tsx
  src/api/alcoholData.tsx
  src/api/userData.tsx
  vite.config.ts
Labels: feat

#52 Fix#51 detail/toggle
  src/@components/detailPage/detailProduct/successBuyButton.tsx
  src/@components/orderPaymentPage/paymentConfirmation/ amountOfPayment.tsx
  src/@components/orderPaymentPage/successModal.tsx
  src/Router.tsx
Labels: feat, fix, design

#53 [ feat ] TopButton
  src/@components/homePage/banner.tsx
  src/@components/homePage/topButton.tsx
  src/@pages/home.tsx
  src/assets/icon/topButtonIc.svg
  src/assets/index.ts
  vite.config.ts
Labels: feat, design
